services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: db_medicos
      MYSQL_USER: usuario_medicos
      MYSQL_PASSWORD: senha_medicos
    ports:
      - "3306:3306"
  
  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=usuario_medicos
      - DB_PASSWORD=senha_medicos
      - DB_NAME=db_medicos
    depends_on:
      - db

volumes:
  mysql-data:
